name: Runner Test

on:
  push:

jobs:
  runner-test:
    runs-on: batcave-node22

    steps:
      - name: Environment
        run: |
          echo "Batcave Runner OK"
          node --version
          pnpm --version
